apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Cluster resources you DO want Flux to manage for this env
  - namespace/
  - elastic/
  - flux-system/
# IMPORTANT: do NOT list flux-system/ here, or Flux will self-manage
# its own GitRepository/Kustomization and overwrite your .env changes.
