apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-sync
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: app-source
  path: ./clusters/elk # <-- this is where your cluster stuff lives
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrepo-elastic.yaml
